#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoraPic
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class NoraPic : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPicManagement(PicManagement instance);
    partial void UpdatePicManagement(PicManagement instance);
    partial void DeletePicManagement(PicManagement instance);
    #endregion
		
		public NoraPic(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NoraPic(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NoraPic(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NoraPic(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<@__VERSION> @__VERSION
		{
			get
			{
				return this.GetTable<@__VERSION>();
			}
		}
		
		public System.Data.Linq.Table<PicManagement> PicManagement
		{
			get
			{
				return this.GetTable<PicManagement>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class @__VERSION
	{
		
		private int _SchemaVersion;
		
		private System.DateTime _DateUpdate;
		
		public @__VERSION()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SchemaVersion", DbType="Int NOT NULL")]
		public int SchemaVersion
		{
			get
			{
				return this._SchemaVersion;
			}
			set
			{
				if ((this._SchemaVersion != value))
				{
					this._SchemaVersion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateUpdate", DbType="DateTime NOT NULL")]
		public System.DateTime DateUpdate
		{
			get
			{
				return this._DateUpdate;
			}
			set
			{
				if ((this._DateUpdate != value))
				{
					this._DateUpdate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class PicManagement : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ImageName;
		
		private bool _IsSync;
		
		private bool _IsCached;
		
		private System.Nullable<bool> _IsFav;
		
		private System.DateTime _DateTaken;
		
		private System.Nullable<double> _Latitude;
		
		private System.Nullable<double> _Longitude;
		
		private string _Comments;
		
		private System.Data.Linq.Binary @__version;
		
		private int _Id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnImageNameChanging(string value);
    partial void OnImageNameChanged();
    partial void OnIsSyncChanging(bool value);
    partial void OnIsSyncChanged();
    partial void OnIsCachedChanging(bool value);
    partial void OnIsCachedChanged();
    partial void OnIsFavChanging(System.Nullable<bool> value);
    partial void OnIsFavChanged();
    partial void OnDateTakenChanging(System.DateTime value);
    partial void OnDateTakenChanged();
    partial void OnLatitudeChanging(System.Nullable<double> value);
    partial void OnLatitudeChanged();
    partial void OnLongitudeChanging(System.Nullable<double> value);
    partial void OnLongitudeChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    partial void On_versionChanging(System.Data.Linq.Binary value);
    partial void On_versionChanged();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    #endregion
		
		public PicManagement()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string ImageName
		{
			get
			{
				return this._ImageName;
			}
			set
			{
				if ((this._ImageName != value))
				{
					this.OnImageNameChanging(value);
					this.SendPropertyChanging();
					this._ImageName = value;
					this.SendPropertyChanged("ImageName");
					this.OnImageNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSync", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool IsSync
		{
			get
			{
				return this._IsSync;
			}
			set
			{
				if ((this._IsSync != value))
				{
					this.OnIsSyncChanging(value);
					this.SendPropertyChanging();
					this._IsSync = value;
					this.SendPropertyChanged("IsSync");
					this.OnIsSyncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCached", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool IsCached
		{
			get
			{
				return this._IsCached;
			}
			set
			{
				if ((this._IsCached != value))
				{
					this.OnIsCachedChanging(value);
					this.SendPropertyChanging();
					this._IsCached = value;
					this.SendPropertyChanged("IsCached");
					this.OnIsCachedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsFav", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> IsFav
		{
			get
			{
				return this._IsFav;
			}
			set
			{
				if ((this._IsFav != value))
				{
					this.OnIsFavChanging(value);
					this.SendPropertyChanging();
					this._IsFav = value;
					this.SendPropertyChanged("IsFav");
					this.OnIsFavChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTaken", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime DateTaken
		{
			get
			{
				return this._DateTaken;
			}
			set
			{
				if ((this._DateTaken != value))
				{
					this.OnDateTakenChanging(value);
					this.SendPropertyChanging();
					this._DateTaken = value;
					this.SendPropertyChanged("DateTaken");
					this.OnDateTakenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this.OnLatitudeChanging(value);
					this.SendPropertyChanging();
					this._Latitude = value;
					this.SendPropertyChanged("Latitude");
					this.OnLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this.OnLongitudeChanging(value);
					this.SendPropertyChanging();
					this._Longitude = value;
					this.SendPropertyChanged("Longitude");
					this.OnLongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="NVarChar(1000)", UpdateCheck=UpdateCheck.Never)]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this.OnCommentsChanging(value);
					this.SendPropertyChanging();
					this._Comments = value;
					this.SendPropertyChanged("Comments");
					this.OnCommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="__version", AutoSync=AutoSync.Always, DbType="rowversion", CanBeNull=true, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary _version
		{
			get
			{
				return this.@__version;
			}
			set
			{
				if ((this.@__version != value))
				{
					this.On_versionChanging(value);
					this.SendPropertyChanging();
					this.@__version = value;
					this.SendPropertyChanged("_version");
					this.On_versionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
